apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bsnd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0025-tenant/tkwch-fix-0075-0025-app/devfile-sample-bsnd@sha256:f967573f6a1e420affac1b6dffd2550b608b94a1cfa268194bcc448a84eaa436
        name: my-nodejs
        resources: {}
status: {}
